### PR TITLE
Task3: Product API

### PR DESCRIPTION
**Pull request by Ilya-Valasiuk**
# Front end
* Pull  request - https://github.com/Ilya-Valasiuk/nodejs-aws-fe/pull/2
* Cloud front - https://d3gc8aipmhoxz.cloudfront.net/

# Endpoints:
* GET - https://rm4cc318y5.execute-api.us-east-1.amazonaws.com/dev/api/get-product-list
* GET - https://rm4cc318y5.execute-api.us-east-1.amazonaws.com/dev/api/get-product-list/1
* Invalid params - https://rm4cc318y5.execute-api.us-east-1.amazonaws.com/dev/api/get-product-list/asdf
* Not found - https://rm4cc318y5.execute-api.us-east-1.amazonaws.com/dev/api/get-product-list/40

# Swagger
* https://petstore.swagger.io/?url=https://productservice-swagger.s3.amazonaws.com/swagger.yaml

# What was done
* productList - **done**
* productListById - **done**
* Async/await is used in lambda functions - **done**
* ES6 modules are used for product-service implementation - **done**
* Webpack is configured for product-service - **done**
* SWAGGER documentation is created for product-service - **done**
* Lambda handlers are covered by basic UNIT tests (NO infrastructure logic is needed to be covered) (You may use JEST) - **done**
* Lambda handlers (getProductsList, getProductsById) code is written not in 1 single module (file) and separated in codebase. - **done**
* Main error scenarious are handled by API ("Product not found" error, try catch blocks are used in lambda handlers). - **done**

### CODE REVIEW

**Review by skyRoma — APPROVED** [review]

**Review by skyRoma — COMMENTED** [review]
I can't find any `await` word inside lambdas
But it should be according to the task:
image

**Comment by Ilya-Valasiuk** [comment]
Hi @skyRoma, Thanks for you review. You can see that current lambda functions was done in `async/await` way. If you will remove `async` key word from lambda handler - it will fails because it will work in sync mode. So lambda handlers working async way and it's because I am using `async` key word. I believe it's what we want by the end 👍

**Comment by skyRoma** [comment]
@Ilya-Valasiuk I got you and realized that we understood the tasks differently. The task does not say to write the lambda itself in async/await style but use it inside (**in**) a lambda.

**Comment by Ilya-Valasiuk** [comment]
I believe using async/await **in** lambda without async flow work is impossible. Of Course we can dance with this topic but from my point of view I think this item was addressed to this topic - https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html (**Async handlers** section). It's basic concept how lambda works.

**Comment by skyRoma** [comment]
@Ilya-Valasiuk  Since the problem is only in understanding the task, I won't reduce the score, since I am sure that you would do it  :)

**Pull request merged**
